import {ChangeEvent,useState} from 'react';

type Backup={format:string;version:number;householdId:string;exportedAt:string;tables:Record<string,unknown[]>};
const householdKey='arta.householdId';

export function BackupRestoreMount(){
 const[householdId]=useState(localStorage.getItem(householdKey)||'');
 const[file,setFile]=useState<Backup|null>(null); const[message,setMessage]=useState(''); const[busy,setBusy]=useState(false);
 if(!householdId)return null;
 async function download(){setBusy(true);setMessage('');try{const r=await fetch(`/api/households/${householdId}/backup`);if(!r.ok)throw new Error('Backup gagal dibuat.');const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`arta-${householdId}-backup.json`;a.click();URL.revokeObjectURL(url);setMessage('Backup berhasil dibuat dan diunduh.');}catch(e){setMessage(e instanceof Error?e.message:'Backup gagal.')}finally{setBusy(false)}}
 async function select(e:ChangeEvent<HTMLInputElement>){setMessage('');const f=e.target.files?.[0];if(!f){setFile(null);return}try{const parsed=JSON.parse(await f.text()) as Backup;if(parsed.format!=='arta-household-backup'||parsed.version!==1||parsed.householdId!==householdId)throw new Error('File backup tidak kompatibel dengan household ini.');setFile(parsed);setMessage(`Backup v${parsed.version} siap dipulihkan.`)}catch(err){setFile(null);setMessage(err instanceof Error?err.message:'File backup tidak valid.')}}
 async function restore(){if(!file)return;const ok=window.confirm('Restore akan MENGGANTI seluruh data financial household ini dengan isi backup. Proses tidak dapat dibatalkan. Lanjutkan?');if(!ok)return;setBusy(true);setMessage('');try{const r=await fetch(`/api/households/${householdId}/restore`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true,backup:file})});if(!r.ok){const body=await r.json().catch(()=>({}));throw new Error(body.error||'Restore gagal.')}setMessage('Restore berhasil. Muat ulang halaman untuk melihat data yang dipulihkan.');}catch(e){setMessage(e instanceof Error?e.message:'Restore gagal.')}finally{setBusy(false)}}
 return <section className="panel" aria-labelledby="backup-restore-title"><h2 id="backup-restore-title">Backup & Restore</h2><p>Lindungi seluruh catatan keuangan household tanpa akses langsung ke database.</p><div className="actions"><button disabled={busy} onClick={download}>Download backup</button><label>File backup <input type="file" accept="application/json,.json" disabled={busy} onChange={select}/></label><button disabled={busy||!file} onClick={restore}>Restore backup</button></div><p role="status">{message}</p><p><strong>Perhatian:</strong> restore mengganti data household saat ini. Arta memvalidasi format dan versi sebelum perubahan dilakukan.</p></section>
}
