import React from 'react';
import ReactDOM from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import { App } from './App';
import { BudgetMount } from './BudgetMount';
import { GoalMount } from './GoalMount';
import { ReconciliationMount } from './ReconciliationMount';
import './styles.css';
registerSW({ immediate: true });
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/><BudgetMount/><GoalMount/><ReconciliationMount/></React.StrictMode>);
